# THIS FILE IS AUTOGENERATED. DO NOT CHANGE IT MANUALLY.
#
# It can be regenerated by executing `just update-patient-level-table-definitions`

from ehrql.query_language import CodePatientSeries, DatePatientSeries, PatientLevelTable


class OnsDeaths(PatientLevelTable):
    date: DatePatientSeries
    underlying_cause_of_death: CodePatientSeries
    cause_of_death_01: CodePatientSeries
    cause_of_death_02: CodePatientSeries
    cause_of_death_03: CodePatientSeries
    cause_of_death_04: CodePatientSeries
    cause_of_death_05: CodePatientSeries
    cause_of_death_06: CodePatientSeries
    cause_of_death_07: CodePatientSeries
    cause_of_death_08: CodePatientSeries
    cause_of_death_09: CodePatientSeries
    cause_of_death_10: CodePatientSeries
    cause_of_death_11: CodePatientSeries
    cause_of_death_12: CodePatientSeries
    cause_of_death_13: CodePatientSeries
    cause_of_death_14: CodePatientSeries
    cause_of_death_15: CodePatientSeries
