# THIS FILE IS AUTOGENERATED. DO NOT CHANGE IT MANUALLY.
#
# It can be regenerated by executing `just update-patient-level-table-definitions`

from ehrql.query_language import (
    CodePatientSeries,
    DatePatientSeries,
    FloatPatientSeries,
    IntPatientSeries,
    PatientLevelTable,
    StrPatientSeries,
)


class Isaric(PatientLevelTable):
    age: StrPatientSeries
    age_factor: StrPatientSeries
    calc_age: StrPatientSeries
    sex: StrPatientSeries
    ethnic___1: StrPatientSeries
    ethnic___2: StrPatientSeries
    ethnic___3: StrPatientSeries
    ethnic___4: StrPatientSeries
    ethnic___5: StrPatientSeries
    ethnic___6: StrPatientSeries
    ethnic___7: StrPatientSeries
    ethnic___8: StrPatientSeries
    ethnic___9: StrPatientSeries
    ethnic___10: StrPatientSeries
    covid19_vaccine: StrPatientSeries
    covid19_vaccined: DatePatientSeries
    covid19_vaccine2d: DatePatientSeries
    covid19_vaccined_nk: StrPatientSeries
    corona_ieorres: StrPatientSeries
    coriona_ieorres2: StrPatientSeries
    coriona_ieorres3: StrPatientSeries
    inflammatory_mss: StrPatientSeries
    cestdat: DatePatientSeries
    chrincard: StrPatientSeries
    hypertension_mhyn: StrPatientSeries
    chronicpul_mhyn: StrPatientSeries
    asthma_mhyn: StrPatientSeries
    renal_mhyn: StrPatientSeries
    mildliver: StrPatientSeries
    modliv: StrPatientSeries
    chronicneu_mhyn: StrPatientSeries
    malignantneo_mhyn: StrPatientSeries
    chronichaemo_mhyn: StrPatientSeries
    aidshiv_mhyn: StrPatientSeries
    obesity_mhyn: StrPatientSeries
    diabetes_type_mhyn: StrPatientSeries
    diabetescom_mhyn: StrPatientSeries
    diabetes_mhyn: StrPatientSeries
    rheumatologic_mhyn: StrPatientSeries
    dementia_mhyn: StrPatientSeries
    malnutrition_mhyn: StrPatientSeries
    smoking_mhyn: StrPatientSeries
    hostdat: DatePatientSeries
    hooccur: StrPatientSeries
    hostdat_transfer: DatePatientSeries
    hostdat_transfernk: StrPatientSeries
    readm_cov19: StrPatientSeries
    dsstdat: DatePatientSeries
    dsstdtc: DatePatientSeries


class Medications(PatientLevelTable):
    date: DatePatientSeries
    dmd_code: CodePatientSeries
    consultation_id: IntPatientSeries
    medication_status: IntPatientSeries


class OnsDeaths(PatientLevelTable):
    date: DatePatientSeries
    place: StrPatientSeries
    underlying_cause_of_death: CodePatientSeries
    cause_of_death_01: CodePatientSeries
    cause_of_death_02: CodePatientSeries
    cause_of_death_03: CodePatientSeries
    cause_of_death_04: CodePatientSeries
    cause_of_death_05: CodePatientSeries
    cause_of_death_06: CodePatientSeries
    cause_of_death_07: CodePatientSeries
    cause_of_death_08: CodePatientSeries
    cause_of_death_09: CodePatientSeries
    cause_of_death_10: CodePatientSeries
    cause_of_death_11: CodePatientSeries
    cause_of_death_12: CodePatientSeries
    cause_of_death_13: CodePatientSeries
    cause_of_death_14: CodePatientSeries
    cause_of_death_15: CodePatientSeries


class WlClockstops(PatientLevelTable):
    activity_treatment_function_code: StrPatientSeries
    priority_type_code: StrPatientSeries
    pseudo_organisation_code_patient_pathway_identifier_issuer: StrPatientSeries
    pseudo_patient_pathway_identifier: StrPatientSeries
    pseudo_referral_identifier: StrPatientSeries
    referral_request_received_date: StrPatientSeries
    referral_to_treatment_period_end_date: StrPatientSeries
    referral_to_treatment_period_start_date: StrPatientSeries
    source_of_referral_for_outpatients: StrPatientSeries
    waiting_list_type: StrPatientSeries
    week_ending_date: StrPatientSeries


class WlOpenpathways(PatientLevelTable):
    activity_treatment_function_code: StrPatientSeries
    current_pathway_period_start_date: StrPatientSeries
    priority_type_code: StrPatientSeries
    pseudo_organisation_code_patient_pathway_identifier_issuer: StrPatientSeries
    pseudo_patient_pathway_identifier: StrPatientSeries
    pseudo_referral_identifier: StrPatientSeries
    referral_request_received_date: StrPatientSeries
    referral_to_treatment_period_end_date: StrPatientSeries
    referral_to_treatment_period_start_date: StrPatientSeries
    source_of_referral: StrPatientSeries
    waiting_list_type: StrPatientSeries
    week_ending_date: StrPatientSeries


class ApcsHistorical(PatientLevelTable):
    apcs_ident: IntPatientSeries
    admission_date: DatePatientSeries
    discharge_date: DatePatientSeries
    spell_core_hrg_sus: StrPatientSeries


class ApcsCostHistorical(PatientLevelTable):
    apcs_ident: IntPatientSeries
    grand_total_payment_mff: FloatPatientSeries
    tariff_initial_amount: FloatPatientSeries
    tariff_total_payment: FloatPatientSeries
    admission_date: DatePatientSeries
    discharge_date: DatePatientSeries


class CovidTherapeuticsRaw(PatientLevelTable):
    current_status: StrPatientSeries
    covid_indication: StrPatientSeries
    diagnosis: StrPatientSeries
    intervention: StrPatientSeries
    treatment_start_date: DatePatientSeries
    CASIM05_risk_cohort: StrPatientSeries
    MOL1_high_risk_cohort: StrPatientSeries
    SOT02_risk_cohorts: StrPatientSeries
    form_name: StrPatientSeries
    received: DatePatientSeries
    count: IntPatientSeries
    age_at_received_date: IntPatientSeries
    region: StrPatientSeries
    load_date: DatePatientSeries
