# THIS FILE IS AUTOGENERATED. DO NOT CHANGE IT MANUALLY.
#
# It can be regenerated by executing `just update-patient-level-table-definitions`

from ehrql.query_language import (
    CodePatientSeries,
    DatePatientSeries,
    FloatPatientSeries,
    IntPatientSeries,
    PatientLevelTable,
)


class PracticeRegistrations(PatientLevelTable):
    start_date: DatePatientSeries
    end_date: DatePatientSeries
    practice_pseudo_id: IntPatientSeries


class ClinicalEvents(PatientLevelTable):
    date: DatePatientSeries
    snomedct_code: CodePatientSeries
    numeric_value: FloatPatientSeries


class Medications(PatientLevelTable):
    date: DatePatientSeries
    dmd_code: CodePatientSeries
