# THIS FILE IS AUTOGENERATED. DO NOT CHANGE IT MANUALLY.
#
# It can be regenerated by executing `just update-patient-level-table-definitions`

from ehrql.query_language import (
    BoolPatientSeries,
    CodePatientSeries,
    DatePatientSeries,
    FloatPatientSeries,
    IntPatientSeries,
    MultiCodeStringPatientSeries,
    PatientLevelTable,
    StrPatientSeries,
)


class Addresses(PatientLevelTable):
    address_id: IntPatientSeries
    start_date: DatePatientSeries
    end_date: DatePatientSeries
    address_type: IntPatientSeries
    rural_urban_classification: IntPatientSeries
    imd_rounded: IntPatientSeries
    imd_quintile: StrPatientSeries
    imd_decile: StrPatientSeries
    msoa_code: StrPatientSeries
    has_postcode: BoolPatientSeries
    care_home_is_potential_match: BoolPatientSeries
    care_home_requires_nursing: BoolPatientSeries
    care_home_does_not_require_nursing: BoolPatientSeries


class Apcs(PatientLevelTable):
    apcs_ident: IntPatientSeries
    admission_date: DatePatientSeries
    discharge_date: DatePatientSeries
    discharge_destination: StrPatientSeries
    spell_core_hrg_sus: StrPatientSeries
    admission_method: StrPatientSeries
    primary_diagnosis: CodePatientSeries
    secondary_diagnosis: CodePatientSeries
    all_diagnoses: MultiCodeStringPatientSeries
    all_procedures: MultiCodeStringPatientSeries
    days_in_critical_care: IntPatientSeries
    patient_classification: StrPatientSeries


class ApcsCost(PatientLevelTable):
    apcs_ident: IntPatientSeries
    grand_total_payment_mff: FloatPatientSeries
    tariff_initial_amount: FloatPatientSeries
    tariff_total_payment: FloatPatientSeries
    admission_date: DatePatientSeries
    discharge_date: DatePatientSeries


class Appointments(PatientLevelTable):
    booked_date: DatePatientSeries
    start_date: DatePatientSeries
    seen_date: DatePatientSeries
    status: StrPatientSeries


class ClinicalEvents(PatientLevelTable):
    date: DatePatientSeries
    snomedct_code: CodePatientSeries
    ctv3_code: CodePatientSeries
    numeric_value: FloatPatientSeries
    consultation_id: IntPatientSeries


class ClinicalEventsRanges(PatientLevelTable):
    date: DatePatientSeries
    snomedct_code: CodePatientSeries
    ctv3_code: CodePatientSeries
    numeric_value: FloatPatientSeries
    lower_bound: FloatPatientSeries
    upper_bound: FloatPatientSeries
    comparator: StrPatientSeries
    consultation_id: IntPatientSeries


class CovidTherapeutics(PatientLevelTable):
    covid_indication: StrPatientSeries
    current_status: StrPatientSeries
    intervention: StrPatientSeries
    received: DatePatientSeries
    region: StrPatientSeries
    risk_cohort: StrPatientSeries
    treatment_start_date: DatePatientSeries


class DecisionSupportValues(PatientLevelTable):
    calculation_date: DatePatientSeries
    numeric_value: FloatPatientSeries
    algorithm_description: StrPatientSeries
    algorithm_version: StrPatientSeries


class Ec(PatientLevelTable):
    ec_ident: IntPatientSeries
    arrival_date: DatePatientSeries
    sus_hrg_code: StrPatientSeries


class EcCost(PatientLevelTable):
    ec_ident: IntPatientSeries
    grand_total_payment_mff: FloatPatientSeries
    tariff_total_payment: FloatPatientSeries
    arrival_date: DatePatientSeries
    ec_decision_to_admit_date: DatePatientSeries
    ec_injury_date: DatePatientSeries


class EmergencyCareAttendances(PatientLevelTable):
    id: IntPatientSeries
    arrival_date: DatePatientSeries
    discharge_destination: CodePatientSeries
    diagnosis_01: CodePatientSeries
    diagnosis_02: CodePatientSeries
    diagnosis_03: CodePatientSeries
    diagnosis_04: CodePatientSeries
    diagnosis_05: CodePatientSeries
    diagnosis_06: CodePatientSeries
    diagnosis_07: CodePatientSeries
    diagnosis_08: CodePatientSeries
    diagnosis_09: CodePatientSeries
    diagnosis_10: CodePatientSeries
    diagnosis_11: CodePatientSeries
    diagnosis_12: CodePatientSeries
    diagnosis_13: CodePatientSeries
    diagnosis_14: CodePatientSeries
    diagnosis_15: CodePatientSeries
    diagnosis_16: CodePatientSeries
    diagnosis_17: CodePatientSeries
    diagnosis_18: CodePatientSeries
    diagnosis_19: CodePatientSeries
    diagnosis_20: CodePatientSeries
    diagnosis_21: CodePatientSeries
    diagnosis_22: CodePatientSeries
    diagnosis_23: CodePatientSeries
    diagnosis_24: CodePatientSeries


class Medications(PatientLevelTable):
    consultation_id: IntPatientSeries


class OccupationOnCovidVaccineRecord(PatientLevelTable):
    is_healthcare_worker: BoolPatientSeries


class Opa(PatientLevelTable):
    opa_ident: IntPatientSeries
    appointment_date: DatePatientSeries
    attendance_status: StrPatientSeries
    consultation_medium_used: StrPatientSeries
    first_attendance: StrPatientSeries
    hrg_code: StrPatientSeries
    treatment_function_code: StrPatientSeries


class OpaCost(PatientLevelTable):
    opa_ident: IntPatientSeries
    tariff_opp: FloatPatientSeries
    grand_total_payment_mff: FloatPatientSeries
    tariff_total_payment: FloatPatientSeries
    appointment_date: DatePatientSeries
    referral_request_received_date: DatePatientSeries


class OpaDiag(PatientLevelTable):
    opa_ident: IntPatientSeries
    primary_diagnosis_code: CodePatientSeries
    primary_diagnosis_code_read: CodePatientSeries
    secondary_diagnosis_code_1: CodePatientSeries
    secondary_diagnosis_code_1_read: CodePatientSeries
    appointment_date: DatePatientSeries
    referral_request_received_date: DatePatientSeries


class OpaProc(PatientLevelTable):
    opa_ident: IntPatientSeries
    primary_procedure_code: CodePatientSeries
    primary_procedure_code_read: CodePatientSeries
    procedure_code_2: CodePatientSeries
    procedure_code_2_read: CodePatientSeries
    appointment_date: DatePatientSeries
    referral_request_received_date: DatePatientSeries


class OpenPrompt(PatientLevelTable):
    ctv3_code: CodePatientSeries
    snomedct_code: CodePatientSeries
    creation_date: DatePatientSeries
    consultation_date: DatePatientSeries
    consultation_id: IntPatientSeries
    numeric_value: FloatPatientSeries


class PracticeRegistrations(PatientLevelTable):
    practice_stp: StrPatientSeries
    practice_nuts1_region_name: StrPatientSeries
    practice_systmone_go_live_date: DatePatientSeries


class SgssCovidAllTests(PatientLevelTable):
    specimen_taken_date: DatePatientSeries
    is_positive: BoolPatientSeries
    lab_report_date: DatePatientSeries
    was_symptomatic: BoolPatientSeries
    sgtf_status: IntPatientSeries
    variant: StrPatientSeries
    variant_detection_method: StrPatientSeries


class Ukrr(PatientLevelTable):
    dataset: StrPatientSeries
    renal_centre: StrPatientSeries
    rrt_start_date: DatePatientSeries
    latest_creatinine: FloatPatientSeries
    latest_egfr: FloatPatientSeries
    treatment_modality_start: StrPatientSeries
    treatment_modality_prevalence: StrPatientSeries


class Vaccinations(PatientLevelTable):
    vaccination_id: IntPatientSeries
    date: DatePatientSeries
    target_disease: StrPatientSeries
    product_name: StrPatientSeries


class WlClockstops(PatientLevelTable):
    activity_treatment_function_code: StrPatientSeries
    priority_type_code: StrPatientSeries
    pseudo_organisation_code_patient_pathway_identifier_issuer: StrPatientSeries
    pseudo_patient_pathway_identifier: StrPatientSeries
    pseudo_referral_identifier: StrPatientSeries
    referral_request_received_date: DatePatientSeries
    referral_to_treatment_period_end_date: DatePatientSeries
    referral_to_treatment_period_start_date: DatePatientSeries
    source_of_referral_for_outpatients: StrPatientSeries
    waiting_list_type: StrPatientSeries
    week_ending_date: DatePatientSeries


class WlOpenpathways(PatientLevelTable):
    activity_treatment_function_code: StrPatientSeries
    current_pathway_period_start_date: DatePatientSeries
    priority_type_code: StrPatientSeries
    pseudo_organisation_code_patient_pathway_identifier_issuer: StrPatientSeries
    pseudo_patient_pathway_identifier: StrPatientSeries
    pseudo_referral_identifier: StrPatientSeries
    referral_request_received_date: DatePatientSeries
    referral_to_treatment_period_end_date: DatePatientSeries
    referral_to_treatment_period_start_date: DatePatientSeries
    source_of_referral: StrPatientSeries
    waiting_list_type: StrPatientSeries
    week_ending_date: DatePatientSeries
