#!/bin/bash
# List available commands

set -euo pipefail

echo "Usage:"
echo "    ./scripts/help             prints this help."
echo "    ./scripts/check            runs the format (black), sort (isort) and lint (flake8) check but does not change any files"
echo "    ./scripts/fix              fix formatting and import sort ordering."
echo "    ./scripts/setup            set up production environment."
echo "    ./scripts/dev_setup        set up/update the local dev env."
echo "    ./scripts/run              run the dev project."
echo "    ./scripts/test             run the test suite."
echo "    ./scripts/update           compile and update python dependencies."
