CREATE DATABASE test
  COLLATE SQL_Latin1_General_CP1_CS_AS;
ALTER DATABASE test SET COMPATIBILITY_LEVEL = 100;

CREATE DATABASE temp_tables
  COLLATE SQL_Latin1_General_CP1_CS_AS;
ALTER DATABASE temp_tables SET COMPATIBILITY_LEVEL = 100;

SET QUOTED_IDENTIFIER ON;
GO
