CREATE TABLE p1(patient_id int, i1 int);
CREATE TABLE e1(patient_id int, i1 int);
INSERT INTO p1 values(1, 101);
INSERT INTO p1 values(2, 201);
INSERT INTO p1 values(3, 301);
INSERT INTO p1 values(4, NULL);
INSERT INTO e1 values(1, 101);
INSERT INTO e1 values(2, 201);
INSERT INTO e1 values(2, 203);
INSERT INTO e1 values(3, 333);
INSERT INTO e1 values(3, 334);
INSERT INTO e1 values(4, NULL);

-- Query generated by spec test
-- WITH cte_1 AS
-- (SELECT DISTINCT e1.patient_id AS patient_id
-- FROM e1),
-- cte_2 AS
-- (SELECT cte_1.patient_id AS patient_id
-- FROM cte_1 UNION SELECT p1.patient_id AS patient_id
-- FROM p1),
-- cte_3 AS
-- (SELECT cte_2.patient_id AS patient_id
-- FROM cte_2 LEFT OUTER JOIN cte_1 ON cte_1.patient_id = cte_2.patient_id LEFT OUTER JOIN p1 ON p1.patient_id = cte_2.patient_id
-- WHERE cte_1.patient_id IS NOT NULL OR p1.patient_id IS NOT NULL OR :param_1 = true),
-- cte_4 AS
-- (SELECT e1.patient_id AS patient_id, e1.i1 AS i1
-- FROM e1
-- WHERE e1.patient_id IN (SELECT cte_3.patient_id
-- FROM cte_3))
--  SELECT cte_3.patient_id, EXISTS (SELECT NULL AS anon_1
-- FROM cte_4, p1
-- WHERE cte_4.patient_id = cte_3.patient_id AND cte_4.i1 = p1.i1) AS v
-- FROM cte_3


-- create the with tables from the query
CREATE TABLE cte_1 as SELECT DISTINCT e1.patient_id AS patient_id
FROM e1;
CREATE TABLE cte_2 as SELECT cte_1.patient_id AS patient_id
FROM cte_1 UNION SELECT p1.patient_id AS patient_id
FROM p1;
CREATE TABLE cte_3 as SELECT cte_2.patient_id AS patient_id
FROM cte_2 LEFT OUTER JOIN cte_1 ON cte_1.patient_id = cte_2.patient_id LEFT OUTER JOIN p1 ON p1.patient_id = cte_2.patient_id
WHERE cte_1.patient_id IS NOT NULL OR p1.patient_id IS NOT NULL OR :param_1 = true;
CREATE TABLE cte_4 as SELECT e1.patient_id AS patient_id, e1.i1 AS i1
FROM e1
WHERE e1.patient_id IN (SELECT cte_3.patient_id
FROM cte_3);

-- check contents of tables
SELECT * FROM p1;
-- 1|101
-- 2|201
-- 3|301

SELECT * FROM e1;
-- 1|101
-- 1|102
-- 2|202
-- 3|303

SELECT * FROM cte_1;
-- 1
-- 2
-- 3
SELECT * FROM cte_2;
-- 1
-- 2
-- 3
-- 4
SELECT * FROM cte_3;
-- 1
-- 2
-- 3
-- 4
SELECT * FROM cte_4;
-- 1|101
-- 1|102
-- 2|202
-- 3|303

-- final select query
SELECT cte_3.patient_id, EXISTS (SELECT NULL AS anon_1
FROM cte_4, p1
WHERE cte_4.patient_id = cte_3.patient_id AND cte_4.i1 = p1.i1) AS v
FROM cte_3;
-- 1|1
-- 2|0
-- 3|0
-- 4|0
