on: [push]

jobs:
  deploy:

    permissions:
      contents: read
      deployments: write

    runs-on: ubuntu-24.04

    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Install Python, uv and just
        uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Check docs are current
        run: just docs-check-generated-docs-are-current

      - name: Build site
        run: just docs-build

      - name: Add a version file
        run: echo ${{ github.sha }} > site/version.html

      - name: Publish
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: "cloudflare/wrangler-action@953926a2e2182532811c01a25e53647d93bf07c0" # v4.1.3
        with:
          accountId: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          apiToken: "${{ secrets.CLOUDFLARE_DIRECT_UPLOAD_API_TOKEN }}"
          command: "pages deploy site --project-name=databuilder-docs"
